carrepair/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
]

usuarios/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('add_cliente/', views.add_cliente, name='add_cliente'),
    path('list_clientes/', views.list_clientes, name='list_clientes'),
]

core/models.py
from django.db import models


SEXO = {
    (1, 'Masculino'),
    (2, 'Feminino'),
}


class Pessoa(models.Model):
    nome = models.CharField(max_length=255)
    cpf = models.CharField(max_length=11)
    email = models.EmailField()
    sexo = models.IntegerField(choices=SEXO)

    def __str__(self):
        return f'{self.nome}'

    class Meta:
        db_table = 'pessoa'


class Telefone(models.Model):
    codigoArea = models.CharField(max_length=3)
    celular = models.CharField(max_length=9, unique=True)
    pessoa = models.ForeignKey(Pessoa, related_name='telefone', on_delete=models.CASCADE)

    def __str__(self):
        return f'({self.codigoArea}) {self.celular}'

    class Meta:
        db_table = 'telefone'


class Endereco(models.Model):
    logradouro = models.CharField(max_length=255)
    numero = models.PositiveIntegerField()
    complemento = models.CharField(max_length=150, null=False, blank=True)
    bairro = models.CharField(max_length=150)
    cep = models.CharField(max_length=8)
    cidade = models.CharField(max_length=150)
    estado = models.CharField(max_length=100)
    pessoa = models.ForeignKey(Pessoa, related_name='endereco', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.bairro}, {self.logradouro}, {self.numero}'

    class Meta:
        db_table = 'endereco'

usuarios/models.py
from django.contrib.auth.hashers import make_password
from django.db import models
from core.models import Pessoa


class Funcionario(models.Model):
    password = models.CharField(max_length=255)
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(Funcionario, self).save(*args, **kwargs)

    def __str__(self):
        return self.pessoa.nome

    class Meta:
        db_table = 'funcionario'


class Cliente(models.Model):
    pessoa = models.OneToOneField(Pessoa, on_delete=models.CASCADE)

    def __str__(self):
        return self.pessoa.nome

    class Meta:
        db_table = 'cliente'

usuarios/forms.py
from django import forms
from django.forms import PasswordInput
from .models import Funcionario, Cliente


class FuncionarioForm(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput())

    class Meta:
        model = Funcionario
        fields = ['password', 'pessoa']


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
        exclude = ['pessoa']

usuarios/views.py
from django.shortcuts import render
from django.urls import reverse
from .forms import ClienteForm
from core.forms import PessoaForm, TelefoneForm, EnderecoForm
from django.http import HttpResponseRedirect

from .models import Cliente


def add_cliente(request):
    if request.method == 'POST':
        formCliente = ClienteForm(request.POST)
        formPessoa = PessoaForm(request.POST)
        formEndereco = EnderecoForm(request.POST)
        formTelefone = TelefoneForm(request.POST)
        if formCliente.is_valid() and formPessoa.is_valid() and formEndereco.is_valid() and formTelefone.is_valid():
            pessoa = formPessoa.save()
            telefone = formTelefone.save(commit=False)
            telefone.pessoa = pessoa
            telefone.save()
            endereco = formEndereco.save(commit=False)
            endereco.pessoa = pessoa
            endereco.save()
            cliente = formCliente.save(commit=False)
            cliente.pessoa = pessoa
            cliente.save()
            return HttpResponseRedirect(reverse('add_cliente'))
    else:
        formCliente = ClienteForm()
        formPessoa = PessoaForm()
        formEndereco = EnderecoForm()
        formTelefone = TelefoneForm()

    context = dict(formCliente=formCliente, formPessoa=formPessoa, formEndereco=formEndereco, formTelefone=formTelefone)
    return render(request, 'usuarios/add_cliente.html', context)


def list_clientes(request):
    clientes = Cliente.objects.order_by('id')


    context = {'clientes': clientes}
    return render(request, 'usuarios/list_clientes.html', context)

templates/usuarios/add_cliente.html
{% extends 'base.html' %}
{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#id_cep').blur(function () {
                var cep = $(this).val();
                if (cep) {
                    $.ajax({
                        url: `https://viacep.com.br/ws/${cep}/json/`,
                        type: 'GET',
                        dataType: 'json',
                        success: function (data) {
                            if (!data.erro) {
                                $('#id_logradouro').val(data.logradouro);
                                $('#id_bairro').val(data.bairro);
                                $('#id_cidade').val(data.localidade);
                                $('#id_estado').val(data.uf);
                                $('#id_complemento').val(data.complemento);
                                $('#id_codigoArea').val(data.ddd);
                            } else {
                                alert('CEP não encontrado');
                            }
                        },
                        error: function () {
                            alert('Erro ao buscar o CEP');
                        }
                    })
                }
            })
        });
    </script>
{% endblock script %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'usuarios/css/cadastrarCliente.css' %}">
    <header>
        <h1>Cadastrar Cliente</h1>
    </header>
    <main>
        <form action="{% url 'add_cliente' %}" method="post">
            {% csrf_token %}
            {{ formCliente.as_p }}
            {{ formPessoa.as_p }}
            {{ formEndereco.as_p }}
            {{ formTelefone.as_p }}
            <button type="submit">Adicionar</button>
        </form>
    </main>
{% endblock content %}

templates/usuarios/list_clientes.html
{% extends 'base.html' %}
{% block content %}
    <header>
        <h2>Clientes</h2>
    </header>
    <main>
        {% load static %}
        <link rel="stylesheet" href="{% static 'usuarios/css/listarCliente.css' %}">
        <div class="clientes">
            <div class="row">
                {% for cliente in clientes %}
                    <div class="col-md-3 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h3>Nome: {{ cliente.pessoa.nome }}</h3>
                                <p>CPF: {{ cliente.pessoa.cpf }}</p>

                                <h4>Telefone:</h4>
                                <ul>
                                    {% for telefone in cliente.pessoa.telefone.all %}
                                        <li>({{ telefone.codigoArea }}) {{ telefone.celular }}</li>
                                    {% endfor %}
                                </ul>

                                <h4>Endereço:</h4>
                                <ul>
                                    {% for endereco in cliente.pessoa.endereco.all %}
                                        <li>{{ endereco.logradouro }}, {{ endereco.numero }}
                                            - {{ endereco.bairro }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="card-footer bg-light">
                                <div class="d-flex flex-column gap-2">
                                    <button type="button" class="btn btn-primary" onclick="realizarOrdemServico({{ cliente.id }})">
                                        Realizar Ordem de Serviço
                                    </button>
                                    <a href="{% url 'add_veiculos' cliente.id %}" class="btn btn-primary">Cadastrar Veículo</a>
                                    <a href="listarVeiculo.jsp?id={{ cliente.id }}" class="btn btn-secondary">Listar Veículos</a>
                                    <a href="listarOrdemServico?id={{ cliente.id }}" class="btn btn-secondary">Ordem de Serviços</a>
                                    <a href="editarCliente.jsp?id={{ cliente.id }}&nome={{ cliente.nome }}&endereco={{ cliente.endereco }}&telefone={{ cliente.telefone }}&cpf={{ cliente.cpf }}"
                                       class="btn btn-warning">Editar Dados</a>
                                    <a href="deletarCliente?id={{ cliente.id }}" class="btn btn-danger">Deletar Cliente</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock content %}